services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrum_pokr_app
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production

